import type { User } from './types';

export const mockUsers: User[] = [
  {
    id: 'USR-7812',
    name: 'Alice Miller',
    email: 'alice.m@alpha.co',
    role: 'Admin',
    joinedDate: '2024-01-15',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 12500.0,
    linkedEntities: [
      { entity: 'Google Cloud Project: Alpha', linkedEmail: 'alice.m@alpha.co', usageQueries: 1250, lastActiveInEntity: '1 hr ago' },
      { entity: 'Slack Workspace: Marketing', linkedEmail: 'alice.slack@marketing.co', usageQueries: 4300, lastActiveInEntity: '2 hrs ago' },
      { entity: 'Internal Tool: CMS', linkedEmail: 'alice.miller.cms@co', usageQueries: 780, lastActiveInEntity: '3 hrs ago' },
    ],
  },
  {
    id: 'USR-7901',
    name: 'Bob Johnson',
    email: 'bjohnson99@email.co',
    role: 'Editor',
    joinedDate: '2024-03-03',
    lastActive: '1 day ago',
    subscription: 'Active',
    transactions: 3450.75,
    linkedEntities: [
      { entity: 'GitHub Org: Engineering', linkedEmail: 'bjohnson@github.co', usageQueries: 620, lastActiveInEntity: '1 day ago' },
      { entity: 'Jira Project: Sprint Board', linkedEmail: 'bjohnson@jira.co', usageQueries: 310, lastActiveInEntity: '2 days ago' },
    ],
  },
  {
    id: 'USR-7955',
    name: 'Catherine Lee',
    email: 'clee.design@email.co',
    role: 'Viewer',
    joinedDate: '2024-04-22',
    lastActive: '5 mins ago',
    subscription: 'Pending',
    transactions: 89200.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7956',
    name: 'Diana Morris',
    email: 'dmorris@email.co',
    role: 'Admin',
    joinedDate: '2024-04-22',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 1980.5,
    linkedEntities: [
      { entity: 'AWS Account: Production', linkedEmail: 'dmorris@aws.co', usageQueries: 4100, lastActiveInEntity: '2 hrs ago' },
    ],
  },
  {
    id: 'USR-7907',
    name: 'Eric Thompson',
    email: 'ethompson@email.co',
    role: 'Editor',
    joinedDate: '2024-04-25',
    lastActive: '2 hours ago',
    subscription: 'Inactive',
    transactions: 250000.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7908',
    name: 'Frank Davis',
    email: 'fdavis@email.co',
    role: 'Admin',
    joinedDate: '2024-04-26',
    lastActive: '2 days ago',
    subscription: 'Active',
    transactions: 750.25,
    linkedEntities: [
      { entity: 'Notion Workspace: Ops', linkedEmail: 'fdavis@notion.co', usageQueries: 890, lastActiveInEntity: '2 days ago' },
      { entity: 'Linear Project: Q2 Bugs', linkedEmail: 'fdavis@linear.co', usageQueries: 230, lastActiveInEntity: '3 days ago' },
    ],
  },
  {
    id: 'USR-7950',
    name: 'Maria Santos',
    email: 'msantos@email.co',
    role: 'Editor',
    joinedDate: '2024-04-22',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 6100.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7962',
    name: 'Grace Kim',
    email: 'gkim@email.co',
    role: 'Editor',
    joinedDate: '2024-05-21',
    lastActive: '5 mins ago',
    subscription: 'Pending',
    transactions: 45670.0,
    linkedEntities: [
      { entity: 'Figma Team: Design System', linkedEmail: 'gkim@figma.co', usageQueries: 3200, lastActiveInEntity: '5 mins ago' },
    ],
  },
  {
    id: 'USR-7912',
    name: 'Henry Park',
    email: 'hpark@email.co',
    role: 'Admin',
    joinedDate: '2024-01-25',
    lastActive: '2 days ago',
    subscription: 'Active',
    transactions: 100000.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7920',
    name: 'Isabella Chen',
    email: 'ichen@email.co',
    role: 'Viewer',
    joinedDate: '2024-02-10',
    lastActive: '3 days ago',
    subscription: 'Active',
    transactions: 5400.0,
    linkedEntities: [
      { entity: 'Confluence Space: Wiki', linkedEmail: 'ichen@confluence.co', usageQueries: 150, lastActiveInEntity: '3 days ago' },
    ],
  },
  {
    id: 'USR-7933',
    name: 'James Wilson',
    email: 'jwilson@email.co',
    role: 'Editor',
    joinedDate: '2024-03-18',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 22300.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7941',
    name: 'Karen White',
    email: 'kwhite@email.co',
    role: 'Viewer',
    joinedDate: '2024-06-01',
    lastActive: '4 hours ago',
    subscription: 'Inactive',
    transactions: 800.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7844',
    name: 'Liam Brown',
    email: 'lbrown@email.co',
    role: 'Admin',
    joinedDate: '2024-02-28',
    lastActive: '30 mins ago',
    subscription: 'Active',
    transactions: 67500.0,
    linkedEntities: [
      { entity: 'Datadog Org: Monitoring', linkedEmail: 'lbrown@datadog.co', usageQueries: 5600, lastActiveInEntity: '30 mins ago' },
      { entity: 'PagerDuty Team: On-call', linkedEmail: 'lbrown@pagerduty.co', usageQueries: 120, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-7872',
    name: 'Megan Taylor',
    email: 'mtaylor@email.co',
    role: 'Editor',
    joinedDate: '2024-05-05',
    lastActive: '6 hours ago',
    subscription: 'Pending',
    transactions: 14200.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7889',
    name: 'Nathan Clark',
    email: 'nclark@email.co',
    role: 'Viewer',
    joinedDate: '2024-07-10',
    lastActive: '1 day ago',
    subscription: 'Active',
    transactions: 3300.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7895',
    name: 'Olivia Lewis',
    email: 'olewis@email.co',
    role: 'Admin',
    joinedDate: '2024-08-14',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 41000.0,
    linkedEntities: [
      { entity: 'Salesforce Org: CRM', linkedEmail: 'olewis@sf.co', usageQueries: 2900, lastActiveInEntity: '2 hrs ago' },
    ],
  },
  {
    id: 'USR-7916',
    name: 'Peter Scott',
    email: 'pscott@email.co',
    role: 'Editor',
    joinedDate: '2024-09-01',
    lastActive: '3 hours ago',
    subscription: 'Inactive',
    transactions: 500.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7923',
    name: 'Quinn Adams',
    email: 'qadams@email.co',
    role: 'Viewer',
    joinedDate: '2024-09-15',
    lastActive: '5 hours ago',
    subscription: 'Active',
    transactions: 2200.0,
    linkedEntities: [],
  },
  {
    id: 'USR-7937',
    name: 'Rachel Green',
    email: 'rgreen@email.co',
    role: 'Admin',
    joinedDate: '2024-10-03',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 88000.0,
    linkedEntities: [
      { entity: 'HubSpot Portal: Marketing', linkedEmail: 'rgreen@hubspot.co', usageQueries: 3400, lastActiveInEntity: '1 hr ago' },
      { entity: 'Intercom Workspace', linkedEmail: 'rgreen@intercom.co', usageQueries: 1800, lastActiveInEntity: '2 hrs ago' },
    ],
  },
  {
    id: 'USR-7948',
    name: 'Sam Turner',
    email: 'sturner@email.co',
    role: 'Editor',
    joinedDate: '2024-10-20',
    lastActive: '20 mins ago',
    subscription: 'Active',
    transactions: 9750.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8001',
    name: 'Tara Hughes',
    email: 'thughes@email.co',
    role: 'Viewer',
    joinedDate: '2023-11-05',
    lastActive: '2 days ago',
    subscription: 'Active',
    transactions: 4150.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8002',
    name: 'Umar Patel',
    email: 'upatel@email.co',
    role: 'Admin',
    joinedDate: '2023-12-01',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 53200.0,
    linkedEntities: [
      { entity: 'Azure DevOps: Core', linkedEmail: 'upatel@azure.co', usageQueries: 2100, lastActiveInEntity: '1 hr ago' },
      { entity: 'Okta Org: SSO', linkedEmail: 'upatel@okta.co', usageQueries: 440, lastActiveInEntity: '3 hrs ago' },
    ],
  },
  {
    id: 'USR-8003',
    name: 'Victoria Nash',
    email: 'vnash@email.co',
    role: 'Editor',
    joinedDate: '2024-01-08',
    lastActive: '45 mins ago',
    subscription: 'Active',
    transactions: 18600.0,
    linkedEntities: [
      { entity: 'Webflow Site: Landing', linkedEmail: 'vnash@webflow.co', usageQueries: 670, lastActiveInEntity: '45 mins ago' },
    ],
  },
  {
    id: 'USR-8004',
    name: 'William Foster',
    email: 'wfoster@email.co',
    role: 'Viewer',
    joinedDate: '2024-02-14',
    lastActive: '1 week ago',
    subscription: 'Inactive',
    transactions: 320.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8005',
    name: 'Xena Reyes',
    email: 'xreyes@email.co',
    role: 'Editor',
    joinedDate: '2024-03-22',
    lastActive: '3 hours ago',
    subscription: 'Pending',
    transactions: 7800.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8006',
    name: 'Yusuf Okafor',
    email: 'yokafor@email.co',
    role: 'Admin',
    joinedDate: '2023-09-10',
    lastActive: '10 mins ago',
    subscription: 'Active',
    transactions: 134500.0,
    linkedEntities: [
      { entity: 'AWS Account: Staging', linkedEmail: 'yokafor@aws.co', usageQueries: 8900, lastActiveInEntity: '10 mins ago' },
      { entity: 'Datadog Org: APM', linkedEmail: 'yokafor@datadog.co', usageQueries: 3300, lastActiveInEntity: '20 mins ago' },
      { entity: 'PagerDuty: Infra', linkedEmail: 'yokafor@pd.co', usageQueries: 90, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8007',
    name: 'Zoe Bennett',
    email: 'zbennett@email.co',
    role: 'Viewer',
    joinedDate: '2024-06-18',
    lastActive: '6 hours ago',
    subscription: 'Active',
    transactions: 1100.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8008',
    name: 'Aaron Simmons',
    email: 'asimmons@email.co',
    role: 'Editor',
    joinedDate: '2024-07-04',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 29400.0,
    linkedEntities: [
      { entity: 'GitHub Org: Frontend', linkedEmail: 'asimmons@github.co', usageQueries: 1450, lastActiveInEntity: '2 hrs ago' },
    ],
  },
  {
    id: 'USR-8009',
    name: 'Bella Cooper',
    email: 'bcooper@email.co',
    role: 'Admin',
    joinedDate: '2023-08-22',
    lastActive: '30 mins ago',
    subscription: 'Active',
    transactions: 76800.0,
    linkedEntities: [
      { entity: 'Salesforce: Enterprise', linkedEmail: 'bcooper@sf.co', usageQueries: 4700, lastActiveInEntity: '30 mins ago' },
      { entity: 'HubSpot: Sales', linkedEmail: 'bcooper@hubspot.co', usageQueries: 2200, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8010',
    name: 'Carlos Rivera',
    email: 'crivera@email.co',
    role: 'Viewer',
    joinedDate: '2024-08-30',
    lastActive: '4 days ago',
    subscription: 'Inactive',
    transactions: 0.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8011',
    name: 'Daisy Morgan',
    email: 'dmorgan@email.co',
    role: 'Editor',
    joinedDate: '2024-09-12',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 11250.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8012',
    name: 'Ethan Brooks',
    email: 'ebrooks@email.co',
    role: 'Admin',
    joinedDate: '2023-07-15',
    lastActive: '15 mins ago',
    subscription: 'Active',
    transactions: 210000.0,
    linkedEntities: [
      { entity: 'Google Workspace: Admin', linkedEmail: 'ebrooks@gws.co', usageQueries: 6200, lastActiveInEntity: '15 mins ago' },
      { entity: 'Slack: Engineering', linkedEmail: 'ebrooks@slack.co', usageQueries: 3800, lastActiveInEntity: '20 mins ago' },
      { entity: 'Jira: Platform', linkedEmail: 'ebrooks@jira.co', usageQueries: 1900, lastActiveInEntity: '45 mins ago' },
    ],
  },
  {
    id: 'USR-8013',
    name: 'Fiona Hayes',
    email: 'fhayes@email.co',
    role: 'Viewer',
    joinedDate: '2024-10-07',
    lastActive: '2 hours ago',
    subscription: 'Pending',
    transactions: 450.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8014',
    name: 'George Murphy',
    email: 'gmurphy@email.co',
    role: 'Editor',
    joinedDate: '2024-11-01',
    lastActive: '3 days ago',
    subscription: 'Active',
    transactions: 5900.0,
    linkedEntities: [
      { entity: 'Notion: Product', linkedEmail: 'gmurphy@notion.co', usageQueries: 340, lastActiveInEntity: '3 days ago' },
    ],
  },
  {
    id: 'USR-8015',
    name: 'Hannah Price',
    email: 'hprice@email.co',
    role: 'Admin',
    joinedDate: '2023-06-20',
    lastActive: '5 mins ago',
    subscription: 'Active',
    transactions: 98700.0,
    linkedEntities: [
      { entity: 'AWS: Data Lake', linkedEmail: 'hprice@aws.co', usageQueries: 7100, lastActiveInEntity: '5 mins ago' },
      { entity: 'Snowflake: Analytics', linkedEmail: 'hprice@snowflake.co', usageQueries: 4400, lastActiveInEntity: '10 mins ago' },
    ],
  },
  {
    id: 'USR-8016',
    name: 'Ivan Kowalski',
    email: 'ikowalski@email.co',
    role: 'Viewer',
    joinedDate: '2024-01-30',
    lastActive: '1 week ago',
    subscription: 'Inactive',
    transactions: 175.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8017',
    name: 'Julia Stone',
    email: 'jstone@email.co',
    role: 'Editor',
    joinedDate: '2024-02-22',
    lastActive: '4 hours ago',
    subscription: 'Active',
    transactions: 33100.0,
    linkedEntities: [
      { entity: 'Figma: Brand Assets', linkedEmail: 'jstone@figma.co', usageQueries: 2600, lastActiveInEntity: '4 hrs ago' },
      { entity: 'Canva: Marketing', linkedEmail: 'jstone@canva.co', usageQueries: 980, lastActiveInEntity: '5 hrs ago' },
    ],
  },
  {
    id: 'USR-8018',
    name: 'Kevin Nguyen',
    email: 'knguyen@email.co',
    role: 'Admin',
    joinedDate: '2023-05-14',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 167000.0,
    linkedEntities: [
      { entity: 'GCP: ML Platform', linkedEmail: 'knguyen@gcp.co', usageQueries: 9400, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8019',
    name: 'Laura Flores',
    email: 'lflores@email.co',
    role: 'Viewer',
    joinedDate: '2024-03-05',
    lastActive: '2 days ago',
    subscription: 'Active',
    transactions: 2800.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8020',
    name: 'Marco Rossi',
    email: 'mrossi@email.co',
    role: 'Editor',
    joinedDate: '2024-04-10',
    lastActive: '6 hours ago',
    subscription: 'Pending',
    transactions: 16400.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8021',
    name: 'Nina Johansson',
    email: 'njohansson@email.co',
    role: 'Admin',
    joinedDate: '2023-10-28',
    lastActive: '25 mins ago',
    subscription: 'Active',
    transactions: 44300.0,
    linkedEntities: [
      { entity: 'Linear: Roadmap Q1', linkedEmail: 'njohansson@linear.co', usageQueries: 1700, lastActiveInEntity: '25 mins ago' },
      { entity: 'Confluence: Engineering', linkedEmail: 'njohansson@confluence.co', usageQueries: 560, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8022',
    name: 'Oscar Mendez',
    email: 'omendez@email.co',
    role: 'Viewer',
    joinedDate: '2024-05-19',
    lastActive: '3 hours ago',
    subscription: 'Active',
    transactions: 920.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8023',
    name: 'Priya Sharma',
    email: 'psharma@email.co',
    role: 'Editor',
    joinedDate: '2024-06-08',
    lastActive: '50 mins ago',
    subscription: 'Active',
    transactions: 27600.0,
    linkedEntities: [
      { entity: 'GitHub: Data Science', linkedEmail: 'psharma@github.co', usageQueries: 3100, lastActiveInEntity: '50 mins ago' },
    ],
  },
  {
    id: 'USR-8024',
    name: 'Ryan O\'Brien',
    email: 'robrien@email.co',
    role: 'Admin',
    joinedDate: '2023-04-02',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 320500.0,
    linkedEntities: [
      { entity: 'AWS: Finance Prod', linkedEmail: 'robrien@aws.co', usageQueries: 11200, lastActiveInEntity: '2 hrs ago' },
      { entity: 'Splunk: Security', linkedEmail: 'robrien@splunk.co', usageQueries: 4600, lastActiveInEntity: '3 hrs ago' },
      { entity: 'Okta: Enterprise SSO', linkedEmail: 'robrien@okta.co', usageQueries: 280, lastActiveInEntity: '4 hrs ago' },
    ],
  },
  {
    id: 'USR-8025',
    name: 'Sofia Andersen',
    email: 'sandersen@email.co',
    role: 'Viewer',
    joinedDate: '2024-07-23',
    lastActive: '5 days ago',
    subscription: 'Inactive',
    transactions: 60.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8026',
    name: 'Thomas Wright',
    email: 'twright@email.co',
    role: 'Editor',
    joinedDate: '2024-08-05',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 8300.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8027',
    name: 'Uma Krishnan',
    email: 'ukrishnan@email.co',
    role: 'Admin',
    joinedDate: '2023-03-17',
    lastActive: '20 mins ago',
    subscription: 'Active',
    transactions: 189000.0,
    linkedEntities: [
      { entity: 'GCP: Big Data', linkedEmail: 'ukrishnan@gcp.co', usageQueries: 14300, lastActiveInEntity: '20 mins ago' },
      { entity: 'Looker: BI Dashboards', linkedEmail: 'ukrishnan@looker.co', usageQueries: 5200, lastActiveInEntity: '30 mins ago' },
    ],
  },
  {
    id: 'USR-8028',
    name: 'Victor Petrov',
    email: 'vpetrov@email.co',
    role: 'Viewer',
    joinedDate: '2024-09-27',
    lastActive: '2 hours ago',
    subscription: 'Pending',
    transactions: 1350.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8029',
    name: 'Wendy Larson',
    email: 'wlarson@email.co',
    role: 'Editor',
    joinedDate: '2024-10-14',
    lastActive: '4 hours ago',
    subscription: 'Active',
    transactions: 19800.0,
    linkedEntities: [
      { entity: 'HubSpot: Email Campaigns', linkedEmail: 'wlarson@hubspot.co', usageQueries: 1900, lastActiveInEntity: '4 hrs ago' },
    ],
  },
  {
    id: 'USR-8030',
    name: 'Xavier Dupont',
    email: 'xdupont@email.co',
    role: 'Admin',
    joinedDate: '2023-02-09',
    lastActive: '35 mins ago',
    subscription: 'Active',
    transactions: 445000.0,
    linkedEntities: [
      { entity: 'Azure: Global Prod', linkedEmail: 'xdupont@azure.co', usageQueries: 18700, lastActiveInEntity: '35 mins ago' },
      { entity: 'Datadog: Full Stack', linkedEmail: 'xdupont@datadog.co', usageQueries: 7400, lastActiveInEntity: '40 mins ago' },
      { entity: 'PagerDuty: Global', linkedEmail: 'xdupont@pd.co', usageQueries: 310, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8031',
    name: 'Yasmin El-Amin',
    email: 'yelamin@email.co',
    role: 'Viewer',
    joinedDate: '2024-11-10',
    lastActive: '1 day ago',
    subscription: 'Active',
    transactions: 3700.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8032',
    name: 'Zachary Hunt',
    email: 'zhunt@email.co',
    role: 'Editor',
    joinedDate: '2024-01-19',
    lastActive: '2 hours ago',
    subscription: 'Active',
    transactions: 41600.0,
    linkedEntities: [
      { entity: 'Jira: Infrastructure', linkedEmail: 'zhunt@jira.co', usageQueries: 2800, lastActiveInEntity: '2 hrs ago' },
      { entity: 'Confluence: Ops Runbooks', linkedEmail: 'zhunt@confluence.co', usageQueries: 730, lastActiveInEntity: '3 hrs ago' },
    ],
  },
  {
    id: 'USR-8033',
    name: 'Amara Diallo',
    email: 'adiallo@email.co',
    role: 'Admin',
    joinedDate: '2023-01-11',
    lastActive: '5 mins ago',
    subscription: 'Active',
    transactions: 92400.0,
    linkedEntities: [
      { entity: 'GCP: Security Hub', linkedEmail: 'adiallo@gcp.co', usageQueries: 5500, lastActiveInEntity: '5 mins ago' },
    ],
  },
  {
    id: 'USR-8034',
    name: 'Brandon Walsh',
    email: 'bwalsh@email.co',
    role: 'Viewer',
    joinedDate: '2024-02-03',
    lastActive: '3 days ago',
    subscription: 'Inactive',
    transactions: 240.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8035',
    name: 'Chloe Marsh',
    email: 'cmarsh@email.co',
    role: 'Editor',
    joinedDate: '2024-03-29',
    lastActive: '1 hour ago',
    subscription: 'Active',
    transactions: 13700.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8036',
    name: 'Derek Olsen',
    email: 'dolsen@email.co',
    role: 'Admin',
    joinedDate: '2023-11-25',
    lastActive: '40 mins ago',
    subscription: 'Active',
    transactions: 57900.0,
    linkedEntities: [
      { entity: 'AWS: Developer Tools', linkedEmail: 'dolsen@aws.co', usageQueries: 3600, lastActiveInEntity: '40 mins ago' },
      { entity: 'GitHub: DevOps', linkedEmail: 'dolsen@github.co', usageQueries: 1200, lastActiveInEntity: '1 hr ago' },
    ],
  },
  {
    id: 'USR-8037',
    name: 'Elena Vasquez',
    email: 'evasquez@email.co',
    role: 'Viewer',
    joinedDate: '2024-04-16',
    lastActive: '6 hours ago',
    subscription: 'Active',
    transactions: 4600.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8038',
    name: 'Felix Nguyen',
    email: 'fnguyen@email.co',
    role: 'Editor',
    joinedDate: '2024-05-28',
    lastActive: '2 days ago',
    subscription: 'Pending',
    transactions: 6250.0,
    linkedEntities: [],
  },
  {
    id: 'USR-8039',
    name: 'Gabrielle Morin',
    email: 'gmorin@email.co',
    role: 'Admin',
    joinedDate: '2023-08-06',
    lastActive: '15 mins ago',
    subscription: 'Active',
    transactions: 143200.0,
    linkedEntities: [
      { entity: 'Salesforce: APAC CRM', linkedEmail: 'gmorin@sf.co', usageQueries: 6800, lastActiveInEntity: '15 mins ago' },
      { entity: 'Tableau: Sales Reports', linkedEmail: 'gmorin@tableau.co', usageQueries: 2400, lastActiveInEntity: '30 mins ago' },
      { entity: 'Slack: Sales Team', linkedEmail: 'gmorin@slack.co', usageQueries: 870, lastActiveInEntity: '45 mins ago' },
    ],
  },
  {
    id: 'USR-8040',
    name: 'Hugo Silva',
    email: 'hsilva@email.co',
    role: 'Viewer',
    joinedDate: '2024-06-25',
    lastActive: '1 week ago',
    subscription: 'Inactive',
    transactions: 0.0,
    linkedEntities: [],
  },
];
